### ISSUE TITLE
Add an example

### ISSUE THREAD

**Issue by m3koenig** [khuongduy354/obsidian-visualizer-vscode#1]
I love the idea of this and want to use this but I'm not sure how the links are currently working.
Could you provide an example with some kind of folder structure?

**Comment by m3koenig** [comment]
Oh..found out!
I have to use the same notation as Obsidian. 
Tought it would also use the Markdown link.

**Comment by khuongduy354** [comment]
Thank you for having a look at the project. I thought Obsidian links (wiki links) are more popular, I'll add support for markdown links soon!

**Comment by m3koenig** [comment]
That would be great!
In my use case, I try to use VSCode for notes. I used obsidian and like it. Especially the graph view and miss it in this environment :D But I try to use default markdown notation because of the compability :)
